### ISSUE TITLE
muver keeps asking to run index_reference

### ISSUE THREAD

**Issue by MariusGheorghe** [NIEHS/muver#7]
Hi,

I've pulled the latest docker image for `muver` via `docker pull lavenderca/muver` and mapped my data folder within the docker image.

This is the folder structure:
```
muver@31f527683c00:~$ ls -l
total 20
-rw-r--r-- 1 muver muver  325 Mar 31 14:45 FASTQ_file_list
drwxr-xr-x 2 muver muver 4096 Mar 31 14:12 output
drwxr-xr-x 2 muver muver 4096 Mar 31 14:42 ref_genome
-rw-r--r-- 1 muver muver  455 Mar 31 14:18 run_muver.sh
drwxr-xr-x 2 muver muver 4096 Mar 31 14:11 samples
```
I've generated the reference index and the repeats file:
```
muver@31f527683c00:~$ muver index_reference ref_genome/my_ref_genome.fa
muver@31f527683c00:~$ muver create_repeat_file ref_genome/my_ref_genome.fa
muver@31f527683c00:~$ ls -l ref_genome/
total 9120
-rw-r--r-- 1 muver muver   30427 Mar 31 12:02 my_ref_genome.fa
-rw-r--r-- 1 muver muver 4204544 Mar 31 14:42 my_ref_genome.fa.1.bt2
-rw-r--r-- 1 muver muver    7480 Mar 31 14:42 my_ref_genome.fa.2.bt2
-rw-r--r-- 1 muver muver      17 Mar 31 14:42 my_ref_genome.fa.3.bt2
-rw-r--r-- 1 muver muver    7476 Mar 31 14:42 my_ref_genome.fa.4.bt2
-rw-r--r-- 1 muver muver      26 Mar 31 14:42 my_ref_genome.fa.fai
-rw-r--r-- 1 muver muver 4204544 Mar 31 14:42 my_ref_genome.fa.rev.1.bt2
-rw-r--r-- 1 muver muver    7480 Mar 31 14:42 my_ref_genome.fa.rev.2.bt2
-rw-r--r-- 1 muver muver    7480 Mar 31 14:42 my_ref_genome.repeats
```

When tryin to launch the pipeline via:
```
muver@31f527683c00:~$ muver run_pipeline ref_genome/my_ref_genome.fa FASTQ_file_list my_ref_genome output/
```
I get

```
Reference assembly not indexed. Run "muver index_reference".
```

I tried re-generating the index files, giving the location with an absolute path instead of relative, putting the files in the current folder, but I get the same error over and over again : /

On top of this, there is no way for me to install a text editor in the docker image, because I cannot root. There is practically nothing I can do to modify the python code to put at least some print messages and see where it looks for the files and why it sees the FASTA file of the reference genome but not the index, while this function from your code, looks to be correct:
```
def check_reference_indices(ref_fn):
    '''
    For a given reference FASTA file, check for reference indices.
    '''
    # Bowtie2 and samtools suffixes
    suffixes = [
        '.1.bt2',
        '.2.bt2',
        '.3.bt2',
        '.4.bt2',
        '.rev.1.bt2',
        '.rev.2.bt2',
        '.fai',
    ]
....
....
```
Any idea what is going on?

If I try to install `muver` from your GIT repo, I get caught up in installing the dependencies, where you require some specific GATK version, where their build just fails.. yaay super java.. and it's not clear what path you need for Picard. 

Plus, you do not make the Dockerfile available so I can customize it, which IMO is not good practice. 

Thanks in advance for your help.

Marius

**Comment by burkholderab** [comment]
Hi Marius,

In your ref_genome folder, I don’t see a sequence dictionary file (my_ref_genome.dict) that should have been generated by Picard tools. Make sure to download the Picard jar file, version 2.9.2 or greater should work, and to mount it when you launch docker using:

-v /full/path/to/picard.jar:/home/muver/picard.jar

You’ll have to do this for the GATK 3.7 jar file as well:

-v /full/path/to/GenomeAnalysisTK.jar:/home/muver/GenomeAnalysisTK.jar

You can download the specific version of GATK here:  https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-0-ge9d806836.tar.bz2

You can test that these jar files have been successfully mapped by running the following commands in /home/muver within the container:

java -jar picard.jar -h
java -jar GenomeAnalysisTK.jar --help

Thanks for the feedback on the container’s organization. I plan to update it in the near future to improve its overall usability.

Adam

**Comment by MariusGheorghe** [comment]
Hi Adam,

Thank you for your reply and all the details. 

I thought that all dependencies are **inside** the Docker image to ease up the usage, but I see now that I still have to install (at least) two of the dependencies locally.

When I was trying to install `muver` from the repo directly, I got thrown off by other errors in the GATK installation (which I know it's a mess and changes with every new version they release.. been there.. done that :dagger: ).

Will give it a try following your instructions and hopefully this time i'll get it to work.

Thank you once again. Will get back to you if successful or not so we can (eventually) close this issue.

Marius

**Comment by MariusGheorghe** [comment]
Hi again,

As promised, I'm getting back to you with feedback.
Following your instructions, I got it to work. At least it seems so :]

Just as a suggestion, it is easier if you point the users to install GenomeAnalysisTK instead of the entire GATK suite as you mentioned in your reply: https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-0-ge9d806836.tar.bz2

Once again, thank you for your support and looking forward to the improved Docker image :smirk:

Keep up the good work. Much appreciated.
I consider this issue closed

Marius
