### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by MariusGheorghe** [NIEHS/muver#8]
Hi Adam,

When running the pipeline on FASTA files as described in issue #6 I get the following error:
```
root@68468d084f7d:/home/muver/genomes# muver run_pipeline -p 12 ref_genome/my_genome.fa FASTA_files.txt parent_genome output/

Traceback (most recent call last):   
  File "/usr/local/bin/muver", line 11, in <module>
    load_entry_point('muver==0.1.0', 'console_scripts', 'muver')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/muver-0.1.0-py2.7.egg/muver/cli.py", line 71, in run_pipeline
    max_records=max_records,
  File "/usr/local/lib/python2.7/dist-packages/muver-0.1.0-py2.7.egg/muver/pipeline.py", line 226, in run_pipeline [s.cnv_regions for s in samples],
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: array must not contain infs or NaNs
``` 

I must specify that I have been getting this error also when running on my FASTA files converted to FASTQ, but I thought this might come from the artificial scores assigned during conversion or whatever.

Do you have any idea what causes this error? Input data malformed or something?
I am unable to tell on which file it crashes because there is no active logging of the file being processed. 

On my side, I'll put some debug prints in your code to grasp what is going on and try to replicate this issue on a smaller data set. Now I'm running it on > 3K genomes.   

Besides that error, I get some runtime warnings from `scipy` and `numpy` (repeatedly) but here are the three places where this is raised:

```
/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:190: RuntimeWarning: Mean of empty slice.
  loc = data.mean()
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount) 
/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:195: RuntimeWarning: Mean of empty slice.
  scale = np.sqrt(((data - loc)**2).mean())
/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:838: RuntimeWarning: invalid value encountered in true_divide
  return n/db/n.sum(), bin_edges
```

Please let me know if you have some insights on the problem. Thank you in advance.

Marius

**Comment by burkholderab** [comment]
Hi Marius,

My best guess is that the NaNs or infs are within the ploidy array being passed to map on that line. Does your FASTQ_list file contain “Ploidy” in the header line, but no values? If so, removing the field from the header or providing one may fix the issue.

I’m not sure if I’ve seen those specific warnings from numpy or scipy in the past, however, I have seen similar warnings in the past. I believe that these could be related to sparseness of the depth or strand bias histograms generated from the data. In my experience, this hasn’t prevented the functions from producing reasonably good fits and estimates of the mean and standard deviation required for downstream processes.

Thanks,

Adam

**Comment by MariusGheorghe** [comment]
Hi Adam,

Thanks for the reply.
No, my FASTQ_file_list contains only two columns: `Sample Name` and `Mate 1 FASTQ`. Tried adding all the columns listed in the manual and leaving them empty, but then `muver` crashes in a different part.

I've also tried to feed empty values or `None` instead of `[s.cnv_regions for s in samples]` on line 226 of the `pipeline.py` file, but no success.
Now, reading a bit on the net about this error, I start to suspect that eventually the runtime warnings that I've mentioned, lead finally to an error. Some are advocating that it might be the `scipy` version and/or `numpy`.

and others suggest to put `np.seterr(divide='ignore', invalid='ignore')` for numpy to "cancel" the runtime warning  for `true_divide`. I'll give it a try.

But yeah... not intuitive at all what's going on :smirk: 

Marius

**Comment by burkholderab** [comment]
Since your jobs have made it to the point of examining depth and strand bias distributions, you should already have fully processed BAM files and the vcf output from HaplotypeCaller. You could try running the remainder of the pipeline individually for each sample, which would require:

muver calculate_bias_distribution
muver calculate_read_depths followed by muver calculate_depth_distribution
muver fit_repeat_indel_rates

You could then run ‘muver call_mutations’ to produce the final results. This will require you to manually generate the “SAMPLE_LIST” file described in the manual that contains the locations of output files from the commands above.

**Comment by MariusGheorghe** [comment]
I do have the BAMs, but not the VCFs. This is what my output folder contains (ran on only 2 genomes for these tests):
```
root@68468d084f7d:/home/muver/genomes/output# ls -Rl
.:
total 76
drwxr-xr-x 2 root root 4096 Apr  2 12:42 bams
drwxr-xr-x 2 root root 4096 Apr  2 12:35 depth_distributions
drwxr-xr-x 2 root root 4096 Apr  2 12:35 filtered_sites
drwxr-xr-x 2 root root 4096 Apr  2 12:35 fits
drwxr-xr-x 2 root root 4096 Apr  2 12:35 gatk_output
drwxr-xr-x 2 root root 4096 Apr  2 12:42 logs
drwxr-xr-x 2 root root 4096 Apr  2 12:35 output
-rw-r--r-- 1 root root   16 Apr  2 12:46 tmpIAdavG.bam.bai
-rw-r--r-- 1 root root   16 Apr  2 12:42 tmpMmaPBM.bam.bai
drwxrw-rw- 2 root root 4096 Apr  2 12:46 tmpNNp1EM
-rw-r--r-- 1 root root   16 Apr  2 12:42 tmpOUG42J.bai
-rw-r--r-- 1 root root   16 Apr  2 12:46 tmpTw4fUD.bai
drwxrw-rw- 2 root root 4096 Apr  2 12:42 tmpX2s2wO
-rw-r--r-- 1 root root   16 Apr  2 12:46 tmp_Blqn3.bai
-rw-r--r-- 1 root root   16 Apr  2 12:42 tmpb6FDcD.bai
drwxrw-rw- 2 root root 4096 Apr  2 12:42 tmpdryOUT
-rw-r--r-- 1 root root   16 Apr  2 12:42 tmpi01nPQ.bam.bai
drwxrw-rw- 2 root root 4096 Apr  2 12:46 tmpmHTnQc
-rw-r--r-- 1 root root   16 Apr  2 12:46 tmprcZrqF.bam.bai

./bams:
total 16
-rw-r--r-- 1 root root 475 Apr  2 12:46 offspring.bam
-rw-r--r-- 1 root root  16 Apr  2 12:46 offspring.bam.bai
-rw-r--r-- 1 root root 477 Apr  2 12:46 parent.bam
-rw-r--r-- 1 root root  16 Apr  2 12:46 parent.bam.bai

./depth_distributions:
total 0

./filtered_sites:
total 0

./fits:
total 0

./gatk_output:
total 0

./logs:
total 12
-rw-r--r-- 1 root root 2435 Apr  2 12:46 haplotype_caller.log
-rw-r--r-- 1 root root 2807 Apr  2 12:46 offspring.realignment.0.log
-rw-r--r-- 1 root root 2807 Apr  2 12:46 parent.realignment.0.log

./output:
total 0

./tmpNNp1EM:
total 0

./tmpX2s2wO:
total 0

./tmpdryOUT:
total 0

./tmpmHTnQc:
total 0
```

and the log of haplotype caller:
```
root@68468d084f7d:/home/muver/genomes/output# more logs/haplotype_caller.log 
INFO  12:46:56,247 HelpFormatter - ------------------------------------------------------------------
---------------- 
INFO  12:46:56,250 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 201
7/07/28 21:26:50 
INFO  12:46:56,251 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
INFO  12:46:56,251 HelpFormatter - For support and documentation go to https://software.broadinstitut
e.org/gatk 
INFO  12:46:56,251 HelpFormatter - [Thu Apr 02 12:46:56 UTC 2020] Executing on Linux 5.0.0-1028-gcp a
md64 
INFO  12:46:56,251 HelpFormatter - OpenJDK 64-Bit Server VM 1.8.0_171-8u171-b11-1~deb9u1-b11 
INFO  12:46:56,256 HelpFormatter - Program Args: -T HaplotypeCaller -o output/gatk_output/haplotype_c
aller_output.vcf -A StrandAlleleCountsBySample -A DepthPerSampleHC -R ref_genome/parent.fa -nct 12
 -mmq 5 -log output/logs/haplotype_caller.log --minPruning 0 --minDanglingBranchLength 0 --pcr_indel_
model NONE -I /home/muver/genomes/output/bams/parent.bam -I /home/muver/genomes/output/bams/offspring.
bam 
INFO  12:46:56,260 HelpFormatter - Executing as root@68468d084f7d on Linux 5.0.0-1028-gcp amd64; Open
JDK 64-Bit Server VM 1.8.0_171-8u171-b11-1~deb9u1-b11. 
INFO  12:46:56,261 HelpFormatter - Date/Time: 2020/04/02 12:46:56 
INFO  12:46:56,261 HelpFormatter - ------------------------------------------------------------------
---------------- 
INFO  12:46:56,261 HelpFormatter - ------------------------------------------------------------------
---------------- 
INFO  12:46:56,418 GenomeAnalysisEngine - Deflater: IntelDeflater 
INFO  12:46:56,419 GenomeAnalysisEngine - Inflater: IntelInflater 
INFO  12:46:56,419 GenomeAnalysisEngine - Strictness is SILENT 
INFO  12:46:56,528 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 
500 
INFO  12:46:56,535 SAMDataSource$SAMReaders - Initializing SAMRecords in serial 
INFO  12:46:56,561 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 0.02 
INFO  12:46:56,572 HCMappingQualityFilter - Filtering out reads with MAPQ < 5 
INFO  12:46:56,576 GenomeAnalysisEngine - Reads file is unmapped. Skipping validation against referen
ce. 
INFO  12:46:56,584 MicroScheduler - Running the GATK in parallel mode with 12 total threads, 12 CPU t
hread(s) for each of 1 data thread(s), of 16 processors available on this machine 
INFO  12:46:56,664 GenomeAnalysisEngine - Preparing for traversal over 2 BAM files 
```

**Comment by burkholderab** [comment]
The sizes of the bam files are extremely small. This is likely the root of the issue. How large are your input FASTA/FASTQ files, and how many reads do they contain?

**Comment by MariusGheorghe** [comment]
Maybe that's the problem? That the VCF is not exported or exported somewhere else? :confused: or maybe it did not manage to finish?

**Comment by MariusGheorghe** [comment]
Well, i have one read per file which is the entire genomic sequence of a virus. So each file has one read and that read is ~30 kilo basepairs

Not enough for `muver`?

**Comment by burkholderab** [comment]
This is likely the cause of the issues you’ve been experiencing. Muver, and all the tools it runs internally are designed to work with data sets where 200-1000bp fragments of genomic DNA have been sequenced from one or both ends, resulting in tens or hundreds of unique observations per genomic position, and a great deal of uncertainty due to errors in PCR and sequencing.

In the past I’ve used mauve, http://darlinglab.org/mauve/mauve.html, to compare small genomes in FASTA format. I’ve only used it to look at 2-3 genomes simultaneously, but you may be able to run your 3000 utilizing the command-line interface.

**Comment by MariusGheorghe** [comment]
OK. Thank you for the clarifications.
I'll give mauve a try then and see how it behaves :]

Thank you once again for all your time and support. 
I consider this issue closed

Marius
