### ISSUE TITLE
Calculating Allele Strand Bias

### ISSUE THREAD

**Issue by KylerAKAnderson** [NIEHS/muver#9]
Looking through the allele strand bias distribution calculation, I noticed these lines.

``` python
elif re.match('[acgt]', bases[i]):
                present_alleles.add(bases[i].upper())
                minus_tally[bases[i]] += 1
```

For context, the code is iterating through the 'read bases' block of an mpileup line (the string `bases` being indexed). Lowercase '[acgt]' indicates a mismatch on the reverse strand. The list `present_alleles` keeps a list of all alleles found on the forward (plus) strand or (i.e. set union) reverse (minus) strand. Counts of the alleles on the strands are kept in separate tallies (`plus_tally` and `minus_tally` for forward and reverse, respectively) and at the end, alleles that appear in both tallies are used to make a ratio for later fitting.

According to this block of code, the reverse strand mismatch indicated by '[acgt]' is recorded in upper case in the allele list, but lower case in the tally. Later in finding allele ratios, the mismatches found on the reverse strand will not be considered, since the lower case allele is not recorded in the list.

A more general phrasing is that allele strand bias ratios are found for alleles that are present on the forward strand and (i.e. set intersection) reverse strand. However, for mismatches, these alleles are recorded as uppercase in the forward strand (plus_) tally, and lowercase in the reverse strand (minus_) tally. The result is that no mismatch alleles are in the intersection, so no allele strand bias ratio is found for mismatches.

Compare this to indels, where the indel sequence is cast to uppercase prior to tallying for both plus and minus cases to make sure they get paired properly when calculating ratios.

**Comment by burkholderab** [comment]
Thanks for catching this. I modified

minus_tally[bases[i]] += 1

to 

minus_tally[bases[i].upper()] += 1

The couple of test runs I performed produced different values for mean and stdev of strand bias, but were still extremely close to those produced by the original code. This isn't surprising, since the vast majority of sequenced bases match the reference genome.
